### ISSUE TITLE
Implement functionality to do multiple searches 

### ISSUE THREAD

**Issue by jrkong** [jrkong/pySearch#6]
If a delimiter is found, pySearch should open a new tab for each subsequent search. Take a look at the [webbrowser](https://docs.python.org/3.7/library/webbrowser.html) module to get started with this.

**Comment by Mera-Gangapersaud** [comment]
I can work on this one

**Comment by jrkong** [comment]
Go for it!

**Comment by jrkong** [comment]
Go for it! I want to link this issue to issue #11 as I would love to have a discussion on the delimiter we'll use for this. However don't let issue #11 block you, a temp delimiter is fine for this issue. The main goal is to implement multiple searches.

**Comment by Mera-Gangapersaud** [comment]
Well I found two different ways to implement multiple searches.
putting searches into quotes:
`pySearch -s "Search one" "Search two"`

or Using the same `-s` option multiple times
`pySearch -s Search one -s search two`

I've gotten both methods to work but the first one makes quotes necessary even when searching one thing so i think the second one is better since it still works without quotes

**Comment by jrkong** [comment]
Merged and closed!

**Comment by jrkong** [comment]
I made a mistake with the PR, I didn't do enough testing. Your changes as they are creates a bit of a regression. This really makes me wish we had tests right now. Sorry about closing and merging prematurely hopefully you don't mind amending the PR(assuming it's still possible) or creating a new PR.
